---
title: "Predictive Policing in Philadelphia"
author: "Frank Chen"
date: "2024-07-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}
library(tidyverse)
library(tidycensus)
library(tigris)
library(sf)
library(ggplot2)
library(scales)
library(extrafont)
library(viridis)
library(raster)
library(spdep)
library(tmap)
library(FNN)
library(grid)
library(gridExtra)
library(kableExtra)
library(classInt)

loadfonts(device = "win")
project_path <- "D:/research/predictive policing/data"
census_api_key("97557b2638bba3200febf4b8196a3444e9628887", overwrite = TRUE)
palette <- c("#c0513d", "#fdb724", "#1ca89d", "#a5bb49")
phl_crs <- "ESRI:102728"
```

```{r functions}
plot.theme <- function(){
  theme(text = element_text(family = "Calibri", size = 16), 
        plot.title = element_text(hjust = 0, face = "bold"),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 14, margin = margin(r = 15, unit = "pt")),
        plot.caption = element_text(size = 12, vjust = -1.5),
        legend.position = "bottom",
        legend.margin = margin(t = 0, unit = "pt"),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 12),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_line(color = "gray85"),
        panel.grid.minor.y = element_line(color = "gray95"))
}

nn_function <- function(measureFrom,measureTo,k) {
  measureFrom_Matrix <-
    as.matrix(measureFrom)
  measureTo_Matrix <-
    as.matrix(measureTo)
  nn <-   
    get.knnx(measureTo, measureFrom, k)$nn.dist
  output <-
    as.data.frame(nn) %>%
    rownames_to_column(var = "thisPoint") %>%
    gather(points, point_distance, V1:ncol(.)) %>%
    arrange(as.numeric(thisPoint)) %>%
    group_by(thisPoint) %>%
    summarize(pointDistance = mean(point_distance)) %>%
    arrange(as.numeric(thisPoint)) %>% 
    dplyr::select(-thisPoint) %>%
    pull()
  
  return(output)  
}
```

## Introduction


## The Current Conditions of Narcotics Possession in Philadelphia

```{r read geo data}
neigh <- 
  st_read(paste0(
    project_path, "/philadelphia-neighborhoods.geojson"
    )) %>% 
  st_transform(crs = phl_crs)
  
po_district <- 
  st_read(paste0(
    project_path, "/Police_District.geojson"
    )) %>% 
  st_transform(crs = phl_crs)

po_serv_area <- 
  st_read(paste0(
    project_path, "/Boundaries_PSA.geojson"
    )) %>% 
  st_transform(crs = phl_crs)
```

```{r read crime data}
crime_22 <- 
  read.csv(paste0(
    project_path, "/crime_incidents_2022.csv"
    ))

crime_23 <- 
  read.csv(paste0(
    project_path, "/crime_incidents_2023.csv"
    ))

felony_22 <- 
  crime_22 %>% 
  filter(ucr_general %in% c("100", "200", "300", "400", "500")) %>% 
  dplyr::select(Y = lat, X = lng) %>%
  na.omit() %>%
  st_as_sf(coords = c("X", "Y"), crs = 4326, agr = "constant") %>%
  st_transform(crs = phl_crs) %>%
  mutate(Legend = "felony")

felony_23 <- 
  crime_23 %>% 
  filter(ucr_general %in% c("100", "200", "300", "400", "500")) %>% 
  dplyr::select(Y = lat, X = lng) %>%
  na.omit() %>%
  st_as_sf(coords = c("X", "Y"), crs = 4326, agr = "constant") %>%
  st_transform(crs = phl_crs) %>%
  mutate(Legend = "felony")
```

```{r 311 data}
pub_ser <- read.csv(paste0(
    project_path, "/public_cases_311.csv"
    ))

abd_vehicle <- 
  pub_ser %>% 
  filter(service_name == "Abandoned Vehicle") %>% 
  dplyr::select(Y = lat, X = lon) %>%
  na.omit() %>%
  st_as_sf(coords = c("X", "Y"), crs = 4326, agr = "constant") %>%
  st_transform(crs = phl_crs) %>%
  mutate(Legend = "Abandoned_Cars")

vac_building <- 
  st_read(paste0(
    project_path, "/Vacant_Indicators_Points.geojson"
    ))

dan_building <- 
  pub_ser %>% 
  filter(service_name == "Dangerous Building Complaint") %>% 
  dplyr::select(Y = lat, X = lon) %>%
  na.omit() %>%
  st_as_sf(coords = c("X", "Y"), crs = 4326, agr = "constant") %>%
  st_transform(crs = phl_crs) %>%
  mutate(Legend = "Dangerous_Building")

graffiti <- 
  pub_ser %>% 
  filter(service_name == "Graffiti Removal") %>% 
  dplyr::select(Y = lat, X = lon) %>%
  na.omit() %>%
  st_as_sf(coords = c("X", "Y"), crs = 4326, agr = "constant") %>%
  st_transform(crs = phl_crs) %>%
  mutate(Legend = "Graffiti")

sanitation <- 
  pub_ser %>% 
  filter(str_detect(service_name, "Sanitation")) %>% 
  dplyr::select(Y = lat, X = lon) %>%
  na.omit() %>%
  st_as_sf(coords = c("X", "Y"), crs = 4326, agr = "constant") %>%
  st_transform(crs = phl_crs) %>%
  mutate(Legend = "Sanitation")

st_light_out <- 
  pub_ser %>% 
  filter(service_name == "Street Light Outage") %>% 
  dplyr::select(Y = lat, X = lon) %>%
  na.omit() %>%
  st_as_sf(coords = c("X", "Y"), crs = 4326, agr = "constant") %>%
  st_transform(crs = phl_crs) %>%
  mutate(Legend = "Street_Light_Outage")

dan_park <- 
  pub_ser %>% 
  filter(service_name == "Parks and Rec Safety and Maintenance") %>% 
  dplyr::select(Y = lat, X = lon) %>%
  na.omit() %>%
  st_as_sf(coords = c("X", "Y"), crs = 4326, agr = "constant") %>%
  st_transform(crs = phl_crs) %>%
  mutate(Legend = "Unsafe_Parks")
```

```{r read business license data}
liq_retail <- 
  st_read(paste0(
    project_path, "/alcohol_shop.geojson"
    ))


bl <- 
  read.csv(paste0(
    project_path, "/business_licenses.csv"
    ))

c <- bl %>% distinct(licensetype)

liq_var <- c("tavern", "Tavern", "TAVERN", "PUB", "Pub", "pub")
liq_var_wrong <- c("publi", "PUBLI", "Publi")

liq_retail <- data.frame()

for (i in liq_var) {
  liq_retail <- 
    bl %>% 
    filter(str_detect(business_name, i)) %>% 
    rbind(liq_retail)
}
d <- liq_retail
for (i in liq_var_wrong) {
  d <- 
    d %>% 
    filter(! str_detect(business_name, i))
}
d <- liq_retail %>% filter(! str_detect(business_name, "public"))


```

```{r traffic data}
# https://www.dvrpc.org/traffic/
# Annual Average Daily Traffic (aadt)
traffic_count <- 
  st_read(paste0(
    project_path, "/Traffic_Count_Locations.geojson"
    )) %>% 
  filter(setyear == "2022") %>% 
  st_transform(crs = phl_crs)
```

